# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'allure-cucumber'
gem 'allure-ruby-adaptor-api'
gem 'appium_console'
gem 'appium_lib'
gem 'appium_lib_core'
gem 'better_errors'
gem 'builder'
gem 'bundler'
gem 'byebug'
gem 'capybara'
gem 'capybara-screenshot'
gem 'coderay'
gem 'colorize'
gem 'compass'
gem 'country_select'
gem 'csv'
gem 'cucumber'
gem 'debase'
gem 'debase-ruby_core_source'
gem 'eventmachine'
gem 'faker'
gem 'ffi'
gem 'flay'
gem 'flog'
gem 'fuubar'
gem 'gherkin'
gem 'geocoder'
gem 'headless'
gem 'json'
gem 'launchy'
gem 'multi_json'
gem 'page-object'
gem 'parallel_tests'
gem 'pry'
gem 'pry-rails'
gem 'pycall'
gem 'poltergeist'
gem 'rake'
gem 'rake-compiler'
gem 'rake-compiler-dock'
gem 'rails'
gem 'require_all'
gem 'rspec'
gem 'rspec-core'
gem 'rspec-example_steps'
gem 'rspec-expectations'
gem 'rubocop-rails'
gem 'ruby-maven'
gem 'screen_capture'
gem 'selenium-webdriver'
gem 'simplecov', require: false, group: :test
gem 'simplecov-html'
gem 'standalone_migrations'
gem 'stripe'
gem 'syntax'
gem 'test-unit'
gem 'titleize'
gem 'touch_action'
gem 'version'
gem 'watir'
gem 'watir-scroll'